name: obaiah_mobile_app
description: Flutter Project With Sdk Version 3.3.10 .

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  alt_sms_autofill: ^1.0.0
  app_settings: ^4.2.0
  path_provider: ^2.0.7 
  cupertino_icons: ^1.0.5
  sms_autofill: ^2.3.0
  flutter_screenutil: ^5.0.0
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.8.4
  firebase_messaging: ^14.2.0
  flutter_local_notifications: ^9.2.0
  flutter:
    sdk: flutter
  flutter_carousel_slider: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_svg: ^2.0.0+1
  fluttertoast: ^8.2.1
  get: ^4.6.5
  get_storage: ^2.0.3
  http: ^0.13.5
  image_picker: ^0.8.7+4
  otp_text_field: ^1.1.3
  pin_code_fields: ^7.4.0
  syncfusion_flutter_signaturepad: ^20.4.48
  video_player: ^2.6.1
  intl: ^0.18.1
  my_fatoorah:
  myfatoorah_flutter: ^2.1.20
  rflutter_alert: ^2.0.7
  cached_network_image: ^3.2.3
  pinput: ^2.2.31
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
  url_launcher: null
  flutter_rating_bar: ^4.0.1
  flutter_credit_card: ^3.0.6
  

dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: "assets/images/app_icon/obaiah_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  # Assets:
  assets:
    - assets/images/
    - assets/images/card/
    - assets/images/apple_icon/
    - assets/images/on_boarding_images/
    - assets/images/payment_images/
    - assets/images/home_images/
    - assets/images/bottom_app_bar_images/
    - assets/images/home_auction_images/
    - assets/images/auction_images/
    - assets/fonts/
    - assets/images/search_filter_images/
    - assets/images/live_auction_images/
    - assets/images/settings_images/
    - assets/images/profile_images/
    - assets/images/wallet_portfolio_images/
    - assets/images/delivery_images/
    - assets/images/app_icon/

  # Fonts:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
