class HomeModel {
  String horseImage,
      owner,
      type,
      color,
      age,
      name,
      height,
      site,
      price,
      time,
      safety,
      fatherName,
      motherName,
      weight,
      sales,
      rating,
      originality,
      isVaccinated,
      status,
      city;
  bool isApprovedByManagement,
      isPaymentTransferred,
      canHorseRide,
      canJumpObstacles,
      isLaundryServiceAvailable,
      isCleaningHoovesServiceAvailable,
      isExerciseServiceAvailable,
      isFeedServiceAvailable,
      isTreatmentServiceAvailable,
      isDailyReportsServiceAvailable,
      isWaitingForApproval,
      isWaitingForDelivery,
      isGreen,
      isSold;

  HomeModel({
    required this.horseImage,
    required this.owner,
    required this.type,
    required this.color,
    required this.age,
    required this.name,
    required this.rating,
    required this.sales,
    required this.height,
    required this.site,
    required this.price,
    required this.safety,
    required this.time,
    required this.fatherName,
    required this.motherName,
    required this.originality,
    required this.weight,
    required this.isVaccinated,
    required this.status,
    required this.isApprovedByManagement,
    required this.isPaymentTransferred,
    required this.city,
    required this.canHorseRide,
    required this.canJumpObstacles,
    required this.isTreatmentServiceAvailable,
    required this.isLaundryServiceAvailable,
    required this.isDailyReportsServiceAvailable,
    required this.isFeedServiceAvailable,
    required this.isExerciseServiceAvailable,
    required this.isCleaningHoovesServiceAvailable,
    this.isGreen = false,
    this.isWaitingForApproval = true,
    this.isWaitingForDelivery = false,
    this.isSold = false,
  });
}
